name: mordidinha
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.0
  fluttertoast: ^8.2.8
  http: ^1.2.2
  flutter_stripe: ^11.3.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.1
  file_picker: ^8.3.1
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

  assets:
    - assets/images/
